before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: B+5P/uXAm8U6pQ2tTnR3nScixylbY6mwTizlweAwwL/nA4ewodEFjMNpKW5GHkEQGfzBWIvRHt+xe+3sCERxqjMAneVbCXuacy4zfSUfbSLaGZIJSiNYFE8HHTgibEE3/LQn+pPNGFGI1xBa0tGwEBiFF/DLPTAQ/6BKAyv50ZIJ+cmAqddLLaTKF6Gb97sIbWy/bOJPFv/4xSDjgbeQzWu52od7o8IdKceKznd5eUEuZ3ZfmbsCb9U8RNQp0HfeXOSXT5Q4MDbUwciXbEVmcicO1pndbUrzt1ih5nMLwTCWI+OJR+hlXmHBhJQmCLiAxwja2D4O7WeeWzLoqYwbabS293lSnD9av6pMVpzppEPo0RVhDUNZ68jZaOugXytHvin+SH/par3Saxj51j/Oq+bRXjjmM5YPBbAJ7eQYmZ8QLJxFgGEDb0D9p0qN8so0znNfx36Tn0vJQ5K8Rko6ADAA6ewXCwnxUykqN/iokKjHCU3T3FF/79JRJ3m+InMZgHtLdvaVKBcbKIFirx3RjeGLeU+aRU5Pl/ZXiQXN9uA/vMc8ChzmQu/SXyjJOf4byQVrRT+G8yZFStdH3mxZpW9+tgnatl24Tc7sp4pMDzZSzyi8ikZIsfM/Gb4IoqFQABft1vr3DeFuUQfylQv7bC6+aKGxdFlVFI+s63wVmjI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
